/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityadmission;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kalab
 */
public class Add_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Add_Admin
     */
    Connection con = databaseConnection.connectdb();
        PreparedStatement ps = null;
        Statement ss = null;
        ResultSet rs = null;
    int  q, i;
    private String gender;
    public Add_Admin() {
        initComponents();
        databaseConnection.connectdb();
        select();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backtoLogin = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        genderLabel = new javax.swing.JPanel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Address = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        Mobile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ViewAdmin = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        DeleteRow = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_user_group_man_man_100px.png"))); // NOI18N
        jLabel2.setText("ADD ADMIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 460, 120));

        backtoLogin.setBackground(new java.awt.Color(51, 153, 255));
        backtoLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backtoLogin.setForeground(new java.awt.Color(255, 255, 255));
        backtoLogin.setText("BACK");
        backtoLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 5, true));
        backtoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoLoginActionPerformed(evt);
            }
        });
        jPanel1.add(backtoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, -1));

        jLabel15.setBackground(new java.awt.Color(237, 143, 3));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(237, 143, 3));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_close_window_40px_1.png"))); // NOI18N
        jLabel15.setToolTipText("EXIT");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 40, 30));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("First/ Given Name*");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        FName.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        FName.setText("admin");
        FName.setToolTipText("right your First Name");
        jPanel1.add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 180, -1));

        LName.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        LName.setToolTipText("right your Last Name");
        jPanel1.add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 180, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Last/ Family Name*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setText("User Name*");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        UserName.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        UserName.setToolTipText("User Name");
        jPanel1.add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 180, -1));

        genderLabel.setBackground(new java.awt.Color(255, 255, 255));
        genderLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        male.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(male);
        male.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(female);
        female.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout genderLabelLayout = new javax.swing.GroupLayout(genderLabel);
        genderLabel.setLayout(genderLabelLayout);
        genderLabelLayout.setHorizontalGroup(
            genderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderLabelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(male)
                .addGap(28, 28, 28)
                .addComponent(female)
                .addGap(46, 46, 46))
        );
        genderLabelLayout.setVerticalGroup(
            genderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderLabelLayout.createSequentialGroup()
                .addGroup(genderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 290, 310, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_broom_30px.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 182, 65));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_login_30px.png"))); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 197, 65));

        Address.setBackground(new java.awt.Color(255, 255, 255));
        Address.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Country *");

        Country.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Country.setToolTipText("re-right your email address");
        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });

        Mobile.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Mobile.setToolTipText("right your Phone");
        Mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobileActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Phone Number*");

        javax.swing.GroupLayout AddressLayout = new javax.swing.GroupLayout(Address);
        Address.setLayout(AddressLayout);
        AddressLayout.setHorizontalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mobile)
                    .addComponent(Country, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addContainerGap())
        );
        AddressLayout.setVerticalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressLayout.createSequentialGroup()
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 370, 330, 120));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Password*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        Password.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        Password.setToolTipText("right your password");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 180, -1));

        ViewAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "UserName", "Password", "A_FName", "A_LName", "gender", "Country", "Mobile"
            }
        ));
        ViewAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ViewAdmin);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 510, 140));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel3.setText("VIEW ADMIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, -1, -1));

        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_edit_profile_50px.png"))); // NOI18N
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 110, 70));

        DeleteRow.setBackground(new java.awt.Color(255, 255, 255));
        DeleteRow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_delete_database_50px.png"))); // NOI18N
        DeleteRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRowActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 340, 110, 70));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Can't be edited");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Can't be edited");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Can't be edited");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Can't be edited");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Can't be edited");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backtoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoLoginActionPerformed
        menu_Admin menu = new menu_Admin();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backtoLoginActionPerformed

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gender = "male";
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gender = "female";
    }//GEN-LAST:event_femaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(FName.getText().isEmpty() || LName.getText().isEmpty() || UserName.getText().isEmpty() || Password.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fill the space indicated..    ");
        }else{

            try{

                String create = "insert into ADMIN values(?,?,?,?,?,?,?)";
                ps = con.prepareStatement(create);
                ps.setString(1,UserName.getText());
                ps.setString(2,Password.getText());
                ps.setString(3,FName.getText());
                ps.setString(4,LName.getText());
                ps.setString(5, gender);
                ps.setString(6,Country.getText());
                ps.setInt(7, Integer.valueOf(Mobile.getText()));
                
                int row = ps.executeUpdate();
                con.close();
                if(JOptionPane.showConfirmDialog(frame, "Create ADMIN Successful   \nGo to menu    " ,"UOG Management System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
                {
                    menu_Admin menu = new menu_Admin();
                    menu.setVisible(true);
                    dispose();
                }else {
                    System.exit(0);
                }

            }catch(SQLException ex){

                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JTextField jtxt = null;
        JPasswordField pass = null;
        JRadioButton rad = null;
        JComboBox con = null;
 
 
        genderGroup.clearSelection();
        for(Component c: jPanel1.getComponents())
        {
            if (c.getClass().toString().contains("javax.swing.JPasswordField"))
            {

                pass = (JPasswordField)c;
                pass.setText(null);
            }
            if (c.getClass().toString().contains("javax.swing.JTextField"))
            {
                jtxt = (JTextField)c;
                jtxt.setText(null);

            }
        }

        for(Component c: Address.getComponents())
        {

            if (c.getClass().toString().contains("javax.swing.JTextField"))
            {
                jtxt = (JTextField)c;
                jtxt.setText(null);

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private JFrame frame;
    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit    ","UOG Management System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel15MouseExited

    private void MobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MobileActionPerformed

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        
        
            String login = "Update UOG.ADMIN set COUNTRY='"+ Country.getText()+"'"+", FNAME='"+ FName.getText()+"'" +"where USERNAME='" + UserName.getText()+"'";
            try{
                ss = con.createStatement();
                ss.executeUpdate(login);
                select();
                JOptionPane.showMessageDialog(null, "Update Successfully press ok...    ");

            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        
    }//GEN-LAST:event_editMouseClicked

    private void DeleteRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRowActionPerformed


            try{

                String UName = UserName.getText();

                String Que = "Delete FROM UOG.ADMIN where USERNAME='" + UName + "'";
                ss = con.createStatement();
                ss.executeUpdate(Que);
                select();
                JOptionPane.showMessageDialog(null, "Deleted Successfully press ok...     ");

            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
//        
    }//GEN-LAST:event_DeleteRowActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void ViewAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAdminMouseClicked
     DefaultTableModel RecordTable = (DefaultTableModel)ViewAdmin.getModel();
       int myindex = ViewAdmin.getSelectedRow();
        UserName.setText(RecordTable.getValueAt(myindex,0).toString());
        FName.setText(RecordTable.getValueAt(myindex,2).toString());
        LName.setText(RecordTable.getValueAt(myindex,3).toString());
        Country.setText(RecordTable.getValueAt(myindex,5).toString());
        Mobile.setText(RecordTable.getValueAt(myindex,6).toString());
    }//GEN-LAST:event_ViewAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Address;
    private javax.swing.JTextField Country;
    private javax.swing.JButton DeleteRow;
    private javax.swing.JTextField FName;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField Mobile;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UserName;
    private javax.swing.JTable ViewAdmin;
    private javax.swing.JButton backtoLogin;
    private javax.swing.JButton edit;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JPanel genderLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    // End of variables declaration//GEN-END:variables

    private void select() {
        
        
            String create = "select * from UOG.ADMIN";
      
       try{
           ps = con.prepareStatement(create);
           rs = ps.executeQuery();
           ViewAdmin.setModel(DbUtils.resultSetToTableModel(rs));
           
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(null, ex);
       }
        
           
                
              
    }
    }

