/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityadmission;

import java.awt.Component;
import javax.swing.*;

import java.sql.*;


/**
 *
 * @author Kalab
 */
public class CreateAccPage extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccPage
     */
        
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
    int  q, i;
    private String gender;
    private String IamA;
    public CreateAccPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        Iam = new javax.swing.ButtonGroup();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backtoLogin = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Mobile = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        retypePassword = new javax.swing.JPasswordField();
        Address = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        A_City = new javax.swing.JTextField();
        A_Country = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        A_Street = new javax.swing.JTextField();
        genderLabel = new javax.swing.JPanel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        describes = new javax.swing.JPanel();
        applying14_15 = new javax.swing.JRadioButton();
        appling16 = new javax.swing.JRadioButton();
        applying17 = new javax.swing.JRadioButton();
        program = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        I_AM = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        DoB = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(114, 11, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_male_user_127px.png"))); // NOI18N
        jLabel2.setText("CREATE ACCOUNT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 460, 120));

        backtoLogin.setBackground(new java.awt.Color(237, 143, 3));
        backtoLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backtoLogin.setForeground(new java.awt.Color(255, 255, 255));
        backtoLogin.setText("BACK");
        backtoLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 143, 3), 5, true));
        backtoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoLoginActionPerformed(evt);
            }
        });
        jPanel1.add(backtoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, -1));

        container.setBackground(new java.awt.Color(237, 143, 3));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("First/ Given Name*");

        Firstname.setBackground(new java.awt.Color(114, 11, 0));
        Firstname.setForeground(new java.awt.Color(255, 255, 255));
        Firstname.setToolTipText("right your First Name");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Date of Birth*");

        Email.setBackground(new java.awt.Color(114, 11, 0));
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setToolTipText("right your Email Address");

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Email Address*");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Last/ Family Name*");

        Lastname.setBackground(new java.awt.Color(114, 11, 0));
        Lastname.setForeground(new java.awt.Color(255, 255, 255));
        Lastname.setToolTipText("right your Last Name");

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Phone Number*");

        Mobile.setBackground(new java.awt.Color(114, 11, 0));
        Mobile.setForeground(new java.awt.Color(255, 255, 255));
        Mobile.setToolTipText("right your Phone");

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Password*");

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Re-Type Password*");

        Password.setBackground(new java.awt.Color(114, 11, 0));
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setToolTipText("right your password");

        retypePassword.setBackground(new java.awt.Color(114, 11, 0));
        retypePassword.setForeground(new java.awt.Color(255, 255, 255));
        retypePassword.setToolTipText("re-right your password");

        Address.setBackground(new java.awt.Color(237, 143, 3));
        Address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Country *");

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setText("City*");

        A_City.setBackground(new java.awt.Color(114, 11, 0));
        A_City.setForeground(new java.awt.Color(255, 255, 255));
        A_City.setToolTipText("re-right your email address");
        A_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_CityActionPerformed(evt);
            }
        });

        A_Country.setBackground(new java.awt.Color(114, 11, 0));
        A_Country.setForeground(new java.awt.Color(255, 255, 255));
        A_Country.setToolTipText("re-right your email address");
        A_Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_CountryActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Street Number");

        A_Street.setBackground(new java.awt.Color(114, 11, 0));
        A_Street.setForeground(new java.awt.Color(255, 255, 255));
        A_Street.setToolTipText("re-right your email address");
        A_Street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_StreetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddressLayout = new javax.swing.GroupLayout(Address);
        Address.setLayout(AddressLayout);
        AddressLayout.setHorizontalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(A_Country, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(A_City, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddressLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(A_Street, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AddressLayout.setVerticalGroup(
            AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressLayout.createSequentialGroup()
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(A_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(A_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(A_Street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        genderLabel.setBackground(new java.awt.Color(237, 143, 3));
        genderLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        male.setBackground(new java.awt.Color(237, 143, 3));
        genderGroup.add(male);
        male.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setBackground(new java.awt.Color(237, 143, 3));
        genderGroup.add(female);
        female.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout genderLabelLayout = new javax.swing.GroupLayout(genderLabel);
        genderLabel.setLayout(genderLabelLayout);
        genderLabelLayout.setHorizontalGroup(
            genderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderLabelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(male)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(female)
                .addGap(46, 46, 46))
        );
        genderLabelLayout.setVerticalGroup(
            genderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genderLabelLayout.createSequentialGroup()
                .addGroup(genderLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        describes.setBackground(new java.awt.Color(237, 143, 3));
        describes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "What best describes You?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 1, 14))); // NOI18N

        applying14_15.setBackground(new java.awt.Color(237, 143, 3));
        Iam.add(applying14_15);
        applying14_15.setText("Appling as a first year student and plan to start University in 2014 and 2015. ");
        applying14_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applying14_15ActionPerformed(evt);
            }
        });

        appling16.setBackground(new java.awt.Color(237, 143, 3));
        Iam.add(appling16);
        appling16.setText("Planning to start University in 2016");
        appling16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appling16ActionPerformed(evt);
            }
        });

        applying17.setBackground(new java.awt.Color(237, 143, 3));
        Iam.add(applying17);
        applying17.setText("Planning to start University in 2017 and beyond");
        applying17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applying17ActionPerformed(evt);
            }
        });

        program.setBackground(new java.awt.Color(114, 11, 0));
        program.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Undergraduate ", "Postgraduate", "Doctrate", " " }));
        program.setSelectedIndex(3);

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setText("In what program do You apply?*");

        I_AM.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        I_AM.setText("I AM*");

        javax.swing.GroupLayout describesLayout = new javax.swing.GroupLayout(describes);
        describes.setLayout(describesLayout);
        describesLayout.setHorizontalGroup(
            describesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(describesLayout.createSequentialGroup()
                .addGroup(describesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(describesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(describesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(applying17)
                            .addComponent(appling16)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(I_AM)
                            .addComponent(applying14_15)))
                    .addGroup(describesLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        describesLayout.setVerticalGroup(
            describesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, describesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(I_AM)
                .addGap(18, 18, 18)
                .addComponent(applying14_15)
                .addGap(18, 18, 18)
                .addComponent(appling16)
                .addGap(18, 18, 18)
                .addComponent(applying17)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(114, 11, 0));
        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_submit_for_approval_80px_1.png"))); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(114, 11, 0));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setText("User Name*");

        UserName.setBackground(new java.awt.Color(114, 11, 0));
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setToolTipText("User Name");

        DoB.setBackground(new java.awt.Color(114, 11, 0));
        DoB.setForeground(new java.awt.Color(114, 11, 0));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Firstname))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(containerLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UserName))
                                    .addGroup(containerLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(Mobile))
                                    .addGroup(containerLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(DoB, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(66, 66, 66))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(retypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(describes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(513, 513, 513))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(describes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(retypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        jPanel1.add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 910, 510));

        jLabel15.setBackground(new java.awt.Color(237, 143, 3));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(237, 143, 3));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_close_window_32px.png"))); // NOI18N
        jLabel15.setToolTipText("EXIT");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void A_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_CityActionPerformed

    private void A_CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_CountryActionPerformed

    private void A_StreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_StreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A_StreetActionPerformed

    private void applying14_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applying14_15ActionPerformed
       IamA = "applying for 2014 or 2015"; 
    }//GEN-LAST:event_applying14_15ActionPerformed

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel15MouseExited
    private JFrame frame;
    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
       frame = new JFrame("EXIT");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit    ","UOG Management System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
             System.exit(0);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void backtoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoLoginActionPerformed
        // TODO add your handling code here:
       
        Login_Page lo = new Login_Page();
        lo.show();
        
        dispose();
    }//GEN-LAST:event_backtoLoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JTextField jtxt = null;
        JPasswordField pass = null;
        JRadioButton rad = null;
        JComboBox con = null;
        
        for(Component c: container.getComponents())
        {
            if (c.getClass().toString().contains("javax.swing.JPasswordField"))
            {
       
                pass = (JPasswordField)c;
                pass.setText(null);
            }
            if (c.getClass().toString().contains("javax.swing.JTextField"))
            {
                jtxt = (JTextField)c;
                jtxt.setText(null);

            }
        }
        
        for(Component c: Address.getComponents())
        {
            
            if (c.getClass().toString().contains("javax.swing.JTextField"))
            {
                jtxt = (JTextField)c;
                jtxt.setText(null);

            }
        }

        
        for(Component c: genderLabel.getComponents())
        {
            if (c.getClass().toString().contains("javax.swing.JRadioButton"))
            {
       
                rad = (JRadioButton)c;
                rad.setContentAreaFilled(false);
            }
            
        }
        
        for(Component c: describes.getComponents())
        {
            if (c.getClass().toString().contains("javax.swing.JComboBox"))
            {
       
                con = (JComboBox)c;
                con.setSelectedIndex(3);
            }
            if (c.getClass().toString().contains("javax.swing.JRadioButton"))
            {
                rad = (JRadioButton)c;
                 rad.setContentAreaFilled(false);

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(Firstname.getText().isEmpty() || Lastname.getText().isEmpty() || Email.getText().isEmpty() || ((JTextField)DoB.getDateEditor().getUiComponent()).getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Fill the space indicated..   ");
         }else{
        
       try{
           
             con =  DriverManager.getConnection("jdbc:derby://localhost:1527/UniversityAdmission","UOG","group3");
             
           String create = "insert into STUDENT values(?,?,?,?,?,?,?,?,?,?,?,?)";
             ps = con.prepareStatement(create);
             ps.setString(1,UserName.getText());
             ps.setString(2,Password.getText());
             ps.setString(3,Firstname.getText());
             ps.setString(4,Lastname.getText());
             ps.setString(5,Email.getText());
             ps.setInt(6, Integer.valueOf(Mobile.getText()));
             ps.setString(7,A_Country.getText());
             ps.setString(8,A_City.getText());
             ps.setString(9,A_Street.getText());
             ps.setString(10, gender);
             ps.setString(11, program.getSelectedItem().toString());
             ps.setString(12,IamA);
           int row = ps.executeUpdate();
           con.close();
            if(JOptionPane.showConfirmDialog(frame, "Create Successful Do you want to Log in?   " ,"UOG Management System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
              Login_Page lo = new Login_Page();
              lo.show();
        
              dispose();
        }else {
                System.exit(0);
            }
               
       }catch(SQLException ex){
           
           JOptionPane.showMessageDialog(null, ex);
       }
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        gender = "male";
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        gender = "female";
    }//GEN-LAST:event_femaleActionPerformed

    private void appling16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appling16ActionPerformed
        IamA = "applying for 2016";
    }//GEN-LAST:event_appling16ActionPerformed

    private void applying17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applying17ActionPerformed
        IamA = "applying for 2017";
    }//GEN-LAST:event_applying17ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A_City;
    private javax.swing.JTextField A_Country;
    private javax.swing.JTextField A_Street;
    private javax.swing.JPanel Address;
    private com.toedter.calendar.JDateChooser DoB;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Firstname;
    private javax.swing.JLabel I_AM;
    private javax.swing.ButtonGroup Iam;
    private javax.swing.JTextField Lastname;
    private javax.swing.JTextField Mobile;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField UserName;
    private javax.swing.JRadioButton appling16;
    private javax.swing.JRadioButton applying14_15;
    private javax.swing.JRadioButton applying17;
    private javax.swing.JButton backtoLogin;
    private javax.swing.JPanel container;
    private javax.swing.JPanel describes;
    private javax.swing.JRadioButton female;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JPanel genderLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JComboBox<String> program;
    private javax.swing.JPasswordField retypePassword;
    // End of variables declaration//GEN-END:variables

    
}
